// <auto-generated />
using System;
using CSIDE.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CSIDE.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241126085248_AddWorkTypesToMaint")]
    partial class AddWorkTypesToMaint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("cside")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CSIDE.Data.Models.Authorization.ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("ApplicationRoles", "cside");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleName = "Administrator"
                        },
                        new
                        {
                            Id = 2,
                            RoleName = "Ranger"
                        },
                        new
                        {
                            Id = 3,
                            RoleName = "RoW Officer"
                        },
                        new
                        {
                            Id = 4,
                            RoleName = "Survey Validator"
                        },
                        new
                        {
                            Id = 5,
                            RoleName = "RoW Statement Editor"
                        });
                });

            modelBuilder.Entity("CSIDE.Data.Models.Authorization.ApplicationUserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<int>("ApplicationRoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "ApplicationRoleId");

                    b.HasIndex("ApplicationRoleId");

                    b.ToTable("ApplicationUserRoles", "cside");
                });

            modelBuilder.Entity("CSIDE.Data.Models.Infrastructure.InfrastructureItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Point>("Geom")
                        .IsRequired()
                        .HasColumnType("geometry (point)");

                    b.Property<double?>("Height")
                        .HasColumnType("double precision");

                    b.Property<int>("InfrastructureTypeId")
                        .HasColumnType("integer");

                    b.Property<LocalDate?>("InstallationDate")
                        .HasColumnType("date");

                    b.Property<double?>("Length")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RouteId")
                        .HasColumnType("text");

                    b.Property<double?>("Width")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("InfrastructureTypeId");

                    b.HasIndex("RouteId");

                    b.ToTable("Infrastructure", "cside");
                });

            modelBuilder.Entity("CSIDE.Data.Models.Infrastructure.InfrastructureType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("InfrastructureTypes", "cside");
                });

            modelBuilder.Entity("CSIDE.Data.Models.Maintenance.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorId")
                        .HasColumnType("text");

                    b.Property<string>("AuthorName")
                        .HasColumnType("text");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Instant>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<int>("JobId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("MaintenanceComments", "cside");
                });

            modelBuilder.Entity("CSIDE.Data.Models.Maintenance.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<LocalDate?>("CompletionDate")
                        .HasColumnType("date");

                    b.Property<int?>("DuplicateJobId")
                        .HasColumnType("integer");

                    b.Property<Point>("Geom")
                        .IsRequired()
                        .HasColumnType("geometry (point)");

                    b.Property<int?>("JobPriorityId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<int?>("JobStatusId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<Instant?>("LogDate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("LoggedById")
                        .HasColumnType("text");

                    b.Property<string>("LoggedByName")
                        .HasColumnType("text");

                    b.Property<int?>("MaintenanceTeamId")
                        .HasColumnType("integer");

                    b.Property<string>("ProblemDescription")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("RouteId")
                        .HasColumnType("text");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("WorkDone")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.HasKey("Id");

                    b.HasIndex("JobPriorityId");

                    b.HasIndex("JobStatusId");

                    b.HasIndex("MaintenanceTeamId");

                    b.HasIndex("RouteId");

                    b.ToTable("MaintenanceJobs", "cside");
                });

            modelBuilder.Entity("CSIDE.Data.Models.Maintenance.JobContact", b =>
                {
                    b.Property<int>("JobId")
                        .HasColumnType("integer");

                    b.Property<int>("ContactId")
                        .HasColumnType("integer");

                    b.HasKey("JobId", "ContactId");

                    b.HasIndex("ContactId");

                    b.ToTable("JobContact", "cside");
                });

            modelBuilder.Entity("CSIDE.Data.Models.Maintenance.JobInfrastructure", b =>
                {
                    b.Property<int>("JobId")
                        .HasColumnType("integer");

                    b.Property<int>("InfrastructureId")
                        .HasColumnType("integer");

                    b.HasKey("JobId", "InfrastructureId");

                    b.HasIndex("InfrastructureId");

                    b.ToTable("JobInfrastructure", "cside");
                });

            modelBuilder.Entity("CSIDE.Data.Models.Maintenance.JobMedia", b =>
                {
                    b.Property<int>("JobId")
                        .HasColumnType("integer");

                    b.Property<int>("MediaId")
                        .HasColumnType("integer");

                    b.HasKey("JobId", "MediaId");

                    b.HasIndex("MediaId");

                    b.ToTable("JobMedia", "cside");
                });

            modelBuilder.Entity("CSIDE.Data.Models.Maintenance.JobPriority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("JobPriorities", "cside");
                });

            modelBuilder.Entity("CSIDE.Data.Models.Maintenance.JobStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FriendlyDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDuplicate")
                        .HasColumnType("boolean");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("JobStatuses", "cside");
                });

            modelBuilder.Entity("CSIDE.Data.Models.Maintenance.JobWorkType", b =>
                {
                    b.Property<int>("JobId")
                        .HasColumnType("integer");

                    b.Property<int>("WorkTypeId")
                        .HasColumnType("integer");

                    b.HasKey("JobId", "WorkTypeId");

                    b.HasIndex("WorkTypeId");

                    b.ToTable("JobWorkTypes", "cside");
                });

            modelBuilder.Entity("CSIDE.Data.Models.Maintenance.MaintenanceTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Polygon>("Geom")
                        .IsRequired()
                        .HasColumnType("geometry (polygon)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MaintenanceTeams", "cside");
                });

            modelBuilder.Entity("CSIDE.Data.Models.Maintenance.WorkType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WorkTypes", "cside");
                });

            modelBuilder.Entity("CSIDE.Data.Models.RoW.Route", b =>
                {
                    b.Property<string>("RouteCode")
                        .HasColumnType("text");

                    b.Property<MultiLineString>("Geom")
                        .IsRequired()
                        .HasColumnType("geometry (multilinestring)");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("RouteCode");

                    b.ToTable("Routes", "cside");
                });

            modelBuilder.Entity("CSIDE.Data.Models.Shared.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ContactTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("OrganisationName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PrimaryContactNo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SecondaryContactNo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ContactTypeId");

                    b.ToTable("Contacts", "cside");
                });

            modelBuilder.Entity("CSIDE.Data.Models.Shared.ContactType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ContactTypes", "cside");
                });

            modelBuilder.Entity("CSIDE.Data.Models.Shared.Media", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Instant?>("UploadDate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.ToTable("Media", "cside");
                });

            modelBuilder.Entity("CSIDE.Data.Models.Authorization.ApplicationUserRole", b =>
                {
                    b.HasOne("CSIDE.Data.Models.Authorization.ApplicationRole", "Role")
                        .WithMany()
                        .HasForeignKey("ApplicationRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CSIDE.Data.Models.Infrastructure.InfrastructureItem", b =>
                {
                    b.HasOne("CSIDE.Data.Models.Infrastructure.InfrastructureType", "InfrastructureType")
                        .WithMany()
                        .HasForeignKey("InfrastructureTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CSIDE.Data.Models.RoW.Route", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId");

                    b.Navigation("InfrastructureType");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("CSIDE.Data.Models.Maintenance.Comment", b =>
                {
                    b.HasOne("CSIDE.Data.Models.Maintenance.Job", "Job")
                        .WithMany("Comments")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("CSIDE.Data.Models.Maintenance.Job", b =>
                {
                    b.HasOne("CSIDE.Data.Models.Maintenance.JobPriority", "JobPriority")
                        .WithMany()
                        .HasForeignKey("JobPriorityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CSIDE.Data.Models.Maintenance.JobStatus", "JobStatus")
                        .WithMany()
                        .HasForeignKey("JobStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CSIDE.Data.Models.Maintenance.MaintenanceTeam", "MaintenanceTeam")
                        .WithMany()
                        .HasForeignKey("MaintenanceTeamId");

                    b.HasOne("CSIDE.Data.Models.RoW.Route", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId");

                    b.Navigation("JobPriority");

                    b.Navigation("JobStatus");

                    b.Navigation("MaintenanceTeam");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("CSIDE.Data.Models.Maintenance.JobContact", b =>
                {
                    b.HasOne("CSIDE.Data.Models.Shared.Contact", "Contact")
                        .WithMany("JobContacts")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CSIDE.Data.Models.Maintenance.Job", "Job")
                        .WithMany("JobContacts")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("CSIDE.Data.Models.Maintenance.JobInfrastructure", b =>
                {
                    b.HasOne("CSIDE.Data.Models.Infrastructure.InfrastructureItem", "Infrastructure")
                        .WithMany()
                        .HasForeignKey("InfrastructureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CSIDE.Data.Models.Maintenance.Job", "Job")
                        .WithMany("JobInfrastructure")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Infrastructure");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("CSIDE.Data.Models.Maintenance.JobMedia", b =>
                {
                    b.HasOne("CSIDE.Data.Models.Maintenance.Job", "Job")
                        .WithMany("JobMedia")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CSIDE.Data.Models.Shared.Media", "Media")
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("CSIDE.Data.Models.Maintenance.JobWorkType", b =>
                {
                    b.HasOne("CSIDE.Data.Models.Maintenance.Job", "Job")
                        .WithMany("WorkTypes")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CSIDE.Data.Models.Maintenance.WorkType", "WorkType")
                        .WithMany()
                        .HasForeignKey("WorkTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("WorkType");
                });

            modelBuilder.Entity("CSIDE.Data.Models.Shared.Contact", b =>
                {
                    b.HasOne("CSIDE.Data.Models.Shared.ContactType", "ContactType")
                        .WithMany()
                        .HasForeignKey("ContactTypeId");

                    b.Navigation("ContactType");
                });

            modelBuilder.Entity("CSIDE.Data.Models.Maintenance.Job", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("JobContacts");

                    b.Navigation("JobInfrastructure");

                    b.Navigation("JobMedia");

                    b.Navigation("WorkTypes");
                });

            modelBuilder.Entity("CSIDE.Data.Models.Shared.Contact", b =>
                {
                    b.Navigation("JobContacts");
                });
#pragma warning restore 612, 618
        }
    }
}
