// <auto-generated />
using System;
using CSIDE.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CSIDE.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241028152724_UpdateGeomOfRouteTable")]
    partial class UpdateGeomOfRouteTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("cside")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CSIDE.Data.Models.Authorization.ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("ApplicationRoles", "cside");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleName = "Administrator"
                        },
                        new
                        {
                            Id = 2,
                            RoleName = "Ranger"
                        },
                        new
                        {
                            Id = 3,
                            RoleName = "RoW Officer"
                        },
                        new
                        {
                            Id = 4,
                            RoleName = "Survey Validator"
                        },
                        new
                        {
                            Id = 5,
                            RoleName = "RoW Statement Editor"
                        });
                });

            modelBuilder.Entity("CSIDE.Data.Models.Authorization.ApplicationUserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<int>("ApplicationRoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "ApplicationRoleId");

                    b.HasIndex("ApplicationRoleId");

                    b.ToTable("ApplicationUserRoles", "cside");
                });

            modelBuilder.Entity("CSIDE.Data.Models.Maintenance.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedToTeamId")
                        .HasColumnType("text");

                    b.Property<LocalDate?>("CompletionDate")
                        .HasColumnType("date");

                    b.Property<Point>("Geom")
                        .IsRequired()
                        .HasColumnType("geometry (point)");

                    b.Property<int?>("JobPriorityId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<int?>("JobStatusId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<Instant?>("LogDate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("LoggedById")
                        .HasColumnType("text");

                    b.Property<string>("LoggedByName")
                        .HasColumnType("text");

                    b.Property<int?>("MaintenanceTeamId")
                        .HasColumnType("integer");

                    b.Property<string>("ProblemDescription")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("RouteId")
                        .HasColumnType("text");

                    b.Property<string>("WorkDone")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.HasKey("Id");

                    b.HasIndex("JobPriorityId");

                    b.HasIndex("JobStatusId");

                    b.HasIndex("MaintenanceTeamId");

                    b.HasIndex("RouteId");

                    b.ToTable("MaintenanceJobs", "cside");
                });

            modelBuilder.Entity("CSIDE.Data.Models.Maintenance.JobPriority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("JobPriorities", "cside");
                });

            modelBuilder.Entity("CSIDE.Data.Models.Maintenance.JobStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FriendlyDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("JobStatuses", "cside");
                });

            modelBuilder.Entity("CSIDE.Data.Models.Maintenance.MaintenanceTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MaintenanceTeams", "cside");
                });

            modelBuilder.Entity("CSIDE.Data.Models.RoW.Route", b =>
                {
                    b.Property<string>("RouteCode")
                        .HasColumnType("text");

                    b.Property<LineString>("Geom")
                        .IsRequired()
                        .HasColumnType("geometry (multilinestring)");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("RouteCode");

                    b.ToTable("Routes", "cside");
                });

            modelBuilder.Entity("CSIDE.Data.Models.Authorization.ApplicationUserRole", b =>
                {
                    b.HasOne("CSIDE.Data.Models.Authorization.ApplicationRole", "Role")
                        .WithMany()
                        .HasForeignKey("ApplicationRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CSIDE.Data.Models.Maintenance.Job", b =>
                {
                    b.HasOne("CSIDE.Data.Models.Maintenance.JobPriority", "JobPriority")
                        .WithMany()
                        .HasForeignKey("JobPriorityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CSIDE.Data.Models.Maintenance.JobStatus", "JobStatus")
                        .WithMany()
                        .HasForeignKey("JobStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CSIDE.Data.Models.Maintenance.MaintenanceTeam", "MaintenanceTeam")
                        .WithMany()
                        .HasForeignKey("MaintenanceTeamId");

                    b.HasOne("CSIDE.Data.Models.RoW.Route", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId");

                    b.Navigation("JobPriority");

                    b.Navigation("JobStatus");

                    b.Navigation("MaintenanceTeam");

                    b.Navigation("Route");
                });
#pragma warning restore 612, 618
        }
    }
}
