trigger:
  tags:
    include:
      - v* # Run on all tags starting with 'v'
pr:
  branches:
    include:
      - main

resources:
  repositories:
    - repository: templates
      type: git
      name: "Web Development/Pipelines"

jobs:
  - template: build/dotnet.yml@templates
    parameters:
      prebuildSteps:
        - task: Npm@1
          inputs:
            command: "install"
            workingDir: "CSIDE.Web"
        - task: Npm@1
          displayName: "Webpack Build (prod)"
          inputs:
            command: "custom"
            customCommand: "run build"
            workingDir: "CSIDE.Web"
  - template: deploy/iis.yml@templates
    parameters:
      environment: "staging"
      websiteName: "gi-staging"
      virtualApplication: "cside"
      variableGroups:
        - "cside-staging-properties"
      projectName: "CSIDE.Web" # Since the project is in the root folder, the project outputs to a folder called s
      dependsOn: build
