// <auto-generated />
using CSIDE.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CSIDE.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("cside")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CSIDE.Data.Models.Authorization.ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("ApplicationRoles", "cside");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleName = "Administrator"
                        },
                        new
                        {
                            Id = 2,
                            RoleName = "Ranger"
                        },
                        new
                        {
                            Id = 3,
                            RoleName = "RoW Officer"
                        },
                        new
                        {
                            Id = 4,
                            RoleName = "Survey Validator"
                        },
                        new
                        {
                            Id = 5,
                            RoleName = "RoW Statement Editor"
                        });
                });

            modelBuilder.Entity("CSIDE.Data.Models.Authorization.ApplicationUserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<int>("ApplicationRoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "ApplicationRoleId");

                    b.HasIndex("ApplicationRoleId");

                    b.ToTable("ApplicationUserRoles", "cside");
                });

            modelBuilder.Entity("CSIDE.Data.Models.Infrastructure.InfrastructureItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Point>("Geom")
                        .IsRequired()
                        .HasColumnType("geometry (point)");

                    b.Property<double?>("Height")
                        .HasColumnType("double precision");

                    b.Property<int>("InfrastructureTypeId")
                        .HasColumnType("integer");

                    b.Property<LocalDate?>("InstallationDate")
                        .HasColumnType("date");

                    b.Property<double?>("Length")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RouteId")
                        .HasColumnType("text");

                    b.Property<double?>("Width")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("InfrastructureTypeId");

                    b.HasIndex("RouteId");

                    b.ToTable("Infrastructure", "cside");
                });

            modelBuilder.Entity("CSIDE.Data.Models.Infrastructure.InfrastructureType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("InfrastructureTypes", "cside");
                });

            modelBuilder.Entity("CSIDE.Data.Models.Maintenance.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorId")
                        .HasColumnType("text");

                    b.Property<string>("AuthorName")
                        .HasColumnType("text");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Instant>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<int>("JobId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("MaintenanceComments", "cside");
                });

            modelBuilder.Entity("CSIDE.Data.Models.Maintenance.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<LocalDate?>("CompletionDate")
                        .HasColumnType("date");

                    b.Property<int?>("DuplicateJobId")
                        .HasColumnType("integer");

                    b.Property<Point>("Geom")
                        .IsRequired()
                        .HasColumnType("geometry (point)");

                    b.Property<int>("JobPriorityId")
                        .HasColumnType("integer");

                    b.Property<int>("JobStatusId")
                        .HasColumnType("integer");

                    b.Property<Instant>("LogDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("LoggedById")
                        .HasColumnType("text");

                    b.Property<string>("LoggedByName")
                        .HasColumnType("text");

                    b.Property<int?>("MaintenanceTeamId")
                        .HasColumnType("integer");

                    b.Property<int?>("ParishId")
                        .HasColumnType("integer");

                    b.Property<string>("ProblemDescription")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("RouteId")
                        .HasColumnType("text");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("WorkDone")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.HasKey("Id");

                    b.HasIndex("JobPriorityId");

                    b.HasIndex("JobStatusId");

                    b.HasIndex("MaintenanceTeamId");

                    b.HasIndex("ParishId");

                    b.HasIndex("RouteId");

                    b.ToTable("MaintenanceJobs", "cside");
                });

            modelBuilder.Entity("CSIDE.Data.Models.Maintenance.JobContact", b =>
                {
                    b.Property<int>("JobId")
                        .HasColumnType("integer");

                    b.Property<int>("ContactId")
                        .HasColumnType("integer");

                    b.HasKey("JobId", "ContactId");

                    b.HasIndex("ContactId");

                    b.ToTable("MaintenanceJobContact", "cside");
                });

            modelBuilder.Entity("CSIDE.Data.Models.Maintenance.JobInfrastructure", b =>
                {
                    b.Property<int>("JobId")
                        .HasColumnType("integer");

                    b.Property<int>("InfrastructureId")
                        .HasColumnType("integer");

                    b.HasKey("JobId", "InfrastructureId");

                    b.HasIndex("InfrastructureId");

                    b.ToTable("MaintenanceJobInfrastructure", "cside");
                });

            modelBuilder.Entity("CSIDE.Data.Models.Maintenance.JobMedia", b =>
                {
                    b.Property<int>("JobId")
                        .HasColumnType("integer");

                    b.Property<int>("MediaId")
                        .HasColumnType("integer");

                    b.HasKey("JobId", "MediaId");

                    b.HasIndex("MediaId");

                    b.ToTable("MaintenanceJobMedia", "cside");
                });

            modelBuilder.Entity("CSIDE.Data.Models.Maintenance.JobPriority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("MaintenanceJobPriorities", "cside");
                });

            modelBuilder.Entity("CSIDE.Data.Models.Maintenance.JobProblemType", b =>
                {
                    b.Property<int>("JobId")
                        .HasColumnType("integer");

                    b.Property<int>("ProblemTypeId")
                        .HasColumnType("integer");

                    b.HasKey("JobId", "ProblemTypeId");

                    b.HasIndex("ProblemTypeId");

                    b.ToTable("MaintenanceJobProblemTypes", "cside");
                });

            modelBuilder.Entity("CSIDE.Data.Models.Maintenance.JobStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FriendlyDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDuplicate")
                        .HasColumnType("boolean");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("MaintenanceJobStatuses", "cside");
                });

            modelBuilder.Entity("CSIDE.Data.Models.Maintenance.ProblemType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("ProblemTypes", "cside");
                });

            modelBuilder.Entity("CSIDE.Data.Models.Maintenance.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Polygon>("Geom")
                        .IsRequired()
                        .HasColumnType("geometry (polygon)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MaintenanceTeams", "cside");
                });

            modelBuilder.Entity("CSIDE.Data.Models.RightsOfWay.LegalStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RouteLegalStatuses", "cside");
                });

            modelBuilder.Entity("CSIDE.Data.Models.RightsOfWay.OperationalStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RouteOperationalStatuses", "cside");
                });

            modelBuilder.Entity("CSIDE.Data.Models.RightsOfWay.Route", b =>
                {
                    b.Property<string>("RouteCode")
                        .HasColumnType("text");

                    b.Property<LocalDate?>("ClosureEndDate")
                        .HasColumnType("date");

                    b.Property<bool>("ClosureIsIndefinite")
                        .HasColumnType("boolean");

                    b.Property<LocalDate?>("ClosureStartDate")
                        .HasColumnType("date");

                    b.Property<MultiLineString>("Geom")
                        .IsRequired()
                        .HasColumnType("geometry (multilinestring)");

                    b.Property<int>("LegalStatusId")
                        .HasColumnType("integer");

                    b.Property<int?>("MaintenanceTeamId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("OperationalStatusId")
                        .HasColumnType("integer");

                    b.Property<int?>("ParishId")
                        .HasColumnType("integer");

                    b.Property<int>("RouteTypeId")
                        .HasColumnType("integer");

                    b.HasKey("RouteCode");

                    b.HasIndex("LegalStatusId");

                    b.HasIndex("MaintenanceTeamId");

                    b.HasIndex("OperationalStatusId");

                    b.HasIndex("ParishId");

                    b.HasIndex("RouteTypeId");

                    b.ToTable("Routes", "cside");
                });

            modelBuilder.Entity("CSIDE.Data.Models.RightsOfWay.RouteMedia", b =>
                {
                    b.Property<string>("RouteId")
                        .HasColumnType("text");

                    b.Property<int>("MediaId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsClosureNotificationDocument")
                        .HasColumnType("boolean");

                    b.HasKey("RouteId", "MediaId");

                    b.HasIndex("MediaId");

                    b.ToTable("RouteMedia", "cside");
                });

            modelBuilder.Entity("CSIDE.Data.Models.RightsOfWay.RouteType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RouteTypes", "cside");
                });

            modelBuilder.Entity("CSIDE.Data.Models.RightsOfWay.Statement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Instant>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("EndGridRef")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("RouteId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StartGridRef")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StatementText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.ToTable("Statements", "cside");
                });

            modelBuilder.Entity("CSIDE.Data.Models.Shared.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ContactTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("OrganisationName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PrimaryContactNo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SecondaryContactNo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ContactTypeId");

                    b.ToTable("Contacts", "cside");
                });

            modelBuilder.Entity("CSIDE.Data.Models.Shared.ContactType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ContactTypes", "cside");
                });

            modelBuilder.Entity("CSIDE.Data.Models.Shared.Media", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Instant>("UploadDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.ToTable("Media", "cside");
                });

            modelBuilder.Entity("CSIDE.Data.Models.Shared.Parish", b =>
                {
                    b.Property<int>("ParishId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("admin_unit_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ParishId"));

                    b.Property<MultiPolygon>("Geom")
                        .IsRequired()
                        .HasColumnType("geometry (multipolygon)")
                        .HasColumnName("geom");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("ParishId");

                    b.ToTable("Parishes", "cside", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("CSIDE.Data.Models.Shared.ParishCode", b =>
                {
                    b.Property<int>("ParishId")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("ParishId", "Code");

                    b.ToTable("ParishCodes", "cside");
                });

            modelBuilder.Entity("CSIDE.Data.Models.Authorization.ApplicationUserRole", b =>
                {
                    b.HasOne("CSIDE.Data.Models.Authorization.ApplicationRole", "Role")
                        .WithMany()
                        .HasForeignKey("ApplicationRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CSIDE.Data.Models.Infrastructure.InfrastructureItem", b =>
                {
                    b.HasOne("CSIDE.Data.Models.Infrastructure.InfrastructureType", "InfrastructureType")
                        .WithMany()
                        .HasForeignKey("InfrastructureTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CSIDE.Data.Models.RightsOfWay.Route", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId");

                    b.Navigation("InfrastructureType");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("CSIDE.Data.Models.Maintenance.Comment", b =>
                {
                    b.HasOne("CSIDE.Data.Models.Maintenance.Job", "Job")
                        .WithMany("Comments")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("CSIDE.Data.Models.Maintenance.Job", b =>
                {
                    b.HasOne("CSIDE.Data.Models.Maintenance.JobPriority", "JobPriority")
                        .WithMany()
                        .HasForeignKey("JobPriorityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CSIDE.Data.Models.Maintenance.JobStatus", "JobStatus")
                        .WithMany()
                        .HasForeignKey("JobStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CSIDE.Data.Models.Maintenance.Team", "MaintenanceTeam")
                        .WithMany()
                        .HasForeignKey("MaintenanceTeamId");

                    b.HasOne("CSIDE.Data.Models.Shared.Parish", "Parish")
                        .WithMany()
                        .HasForeignKey("ParishId");

                    b.HasOne("CSIDE.Data.Models.RightsOfWay.Route", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId");

                    b.Navigation("JobPriority");

                    b.Navigation("JobStatus");

                    b.Navigation("MaintenanceTeam");

                    b.Navigation("Parish");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("CSIDE.Data.Models.Maintenance.JobContact", b =>
                {
                    b.HasOne("CSIDE.Data.Models.Shared.Contact", "Contact")
                        .WithMany("JobContacts")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CSIDE.Data.Models.Maintenance.Job", "Job")
                        .WithMany("JobContacts")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("CSIDE.Data.Models.Maintenance.JobInfrastructure", b =>
                {
                    b.HasOne("CSIDE.Data.Models.Infrastructure.InfrastructureItem", "Infrastructure")
                        .WithMany()
                        .HasForeignKey("InfrastructureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CSIDE.Data.Models.Maintenance.Job", "Job")
                        .WithMany("JobInfrastructure")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Infrastructure");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("CSIDE.Data.Models.Maintenance.JobMedia", b =>
                {
                    b.HasOne("CSIDE.Data.Models.Maintenance.Job", "Job")
                        .WithMany("JobMedia")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CSIDE.Data.Models.Shared.Media", "Media")
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("CSIDE.Data.Models.Maintenance.JobProblemType", b =>
                {
                    b.HasOne("CSIDE.Data.Models.Maintenance.Job", "Job")
                        .WithMany("ProblemTypes")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CSIDE.Data.Models.Maintenance.ProblemType", "ProblemType")
                        .WithMany()
                        .HasForeignKey("ProblemTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("ProblemType");
                });

            modelBuilder.Entity("CSIDE.Data.Models.RightsOfWay.Route", b =>
                {
                    b.HasOne("CSIDE.Data.Models.RightsOfWay.LegalStatus", "LegalStatus")
                        .WithMany()
                        .HasForeignKey("LegalStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CSIDE.Data.Models.Maintenance.Team", "MaintenanceTeam")
                        .WithMany()
                        .HasForeignKey("MaintenanceTeamId");

                    b.HasOne("CSIDE.Data.Models.RightsOfWay.OperationalStatus", "OperationalStatus")
                        .WithMany()
                        .HasForeignKey("OperationalStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CSIDE.Data.Models.Shared.Parish", "Parish")
                        .WithMany()
                        .HasForeignKey("ParishId");

                    b.HasOne("CSIDE.Data.Models.RightsOfWay.RouteType", "RouteType")
                        .WithMany()
                        .HasForeignKey("RouteTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LegalStatus");

                    b.Navigation("MaintenanceTeam");

                    b.Navigation("OperationalStatus");

                    b.Navigation("Parish");

                    b.Navigation("RouteType");
                });

            modelBuilder.Entity("CSIDE.Data.Models.RightsOfWay.RouteMedia", b =>
                {
                    b.HasOne("CSIDE.Data.Models.Shared.Media", "Media")
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CSIDE.Data.Models.RightsOfWay.Route", "Route")
                        .WithMany("RouteMedia")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("CSIDE.Data.Models.RightsOfWay.Statement", b =>
                {
                    b.HasOne("CSIDE.Data.Models.RightsOfWay.Route", "Route")
                        .WithMany("Statements")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");
                });

            modelBuilder.Entity("CSIDE.Data.Models.Shared.Contact", b =>
                {
                    b.HasOne("CSIDE.Data.Models.Shared.ContactType", "ContactType")
                        .WithMany()
                        .HasForeignKey("ContactTypeId");

                    b.Navigation("ContactType");
                });

            modelBuilder.Entity("CSIDE.Data.Models.Shared.ParishCode", b =>
                {
                    b.HasOne("CSIDE.Data.Models.Shared.Parish", "Parish")
                        .WithMany()
                        .HasForeignKey("ParishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parish");
                });

            modelBuilder.Entity("CSIDE.Data.Models.Maintenance.Job", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("JobContacts");

                    b.Navigation("JobInfrastructure");

                    b.Navigation("JobMedia");

                    b.Navigation("ProblemTypes");
                });

            modelBuilder.Entity("CSIDE.Data.Models.RightsOfWay.Route", b =>
                {
                    b.Navigation("RouteMedia");

                    b.Navigation("Statements");
                });

            modelBuilder.Entity("CSIDE.Data.Models.Shared.Contact", b =>
                {
                    b.Navigation("JobContacts");
                });
#pragma warning restore 612, 618
        }
    }
}
