//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSIDE.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSIDE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like you don&apos;t have access to this page. Contact your system administrator to request access.
        /// </summary>
        internal static string Access_Denied_Text {
            get {
                return ResourceManager.GetString("Access Denied Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied.
        /// </summary>
        internal static string Access_Denied_Title {
            get {
                return ResourceManager.GetString("Access Denied Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account details and password are managed by your identity provider..
        /// </summary>
        internal static string Account_Details_Text {
            get {
                return ResourceManager.GetString("Account Details Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new job.
        /// </summary>
        internal static string Create_New_Job_Label {
            get {
                return ResourceManager.GetString("Create New Job Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name.
        /// </summary>
        internal static string Display_Name_Label {
            get {
                return ResourceManager.GetString("Display Name Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DMMO.
        /// </summary>
        internal static string DMMO_Abbreviation {
            get {
                return ResourceManager.GetString("DMMO Abbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definitive Map Modification Orders.
        /// </summary>
        internal static string DMMO_Full_Text {
            get {
                return ResourceManager.GetString("DMMO Full Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! Something went wrong.
        /// </summary>
        internal static string Error_Header_Text {
            get {
                return ResourceManager.GetString("Error Header Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error dealing with your request. If this continues to happen, get in touch with your system administrator.
        /// </summary>
        internal static string Error_Text {
            get {
                return ResourceManager.GetString("Error Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error_Title {
            get {
                return ResourceManager.GetString("Error Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home_Title {
            get {
                return ResourceManager.GetString("Home Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infrastructure.
        /// </summary>
        internal static string Infrastructure_Title {
            get {
                return ResourceManager.GetString("Infrastructure Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landowner Deposits.
        /// </summary>
        internal static string Landowner_Deposits_Title {
            get {
                return ResourceManager.GetString("Landowner Deposits Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string Loading_Text {
            get {
                return ResourceManager.GetString("Loading Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout_Label {
            get {
                return ResourceManager.GetString("Logout Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new maintenance job.
        /// </summary>
        internal static string Maintenance_Create_Title {
            get {
                return ResourceManager.GetString("Maintenance Create Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Job {0}.
        /// </summary>
        internal static string Maintenance_Details_Title {
            get {
                return ResourceManager.GetString("Maintenance Details Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance.
        /// </summary>
        internal static string Maintenance_Title {
            get {
                return ResourceManager.GetString("Maintenance Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage application.
        /// </summary>
        internal static string Manage_Application_Label {
            get {
                return ResourceManager.GetString("Manage Application Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My account.
        /// </summary>
        internal static string My_Account_Label {
            get {
                return ResourceManager.GetString("My Account Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My roles.
        /// </summary>
        internal static string My_Roles_Header {
            get {
                return ResourceManager.GetString("My Roles Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any roles assigned to you.
        /// </summary>
        internal static string No_Roles_Text {
            get {
                return ResourceManager.GetString("No Roles Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPO.
        /// </summary>
        internal static string PPO_Abbreviation {
            get {
                return ResourceManager.GetString("PPO Abbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Path Orders.
        /// </summary>
        internal static string PPO_Full_Text {
            get {
                return ResourceManager.GetString("PPO Full Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary email address.
        /// </summary>
        internal static string Primary_Email_Label {
            get {
                return ResourceManager.GetString("Primary Email Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rights of Way.
        /// </summary>
        internal static string Rights_of_Way_Title {
            get {
                return ResourceManager.GetString("Rights of Way Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These are the roles that have been assigned to you by your system administrator. They control what you can and can&apos;t do in the app..
        /// </summary>
        internal static string Roles_List_Text {
            get {
                return ResourceManager.GetString("Roles List Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surveys.
        /// </summary>
        internal static string Surveys_Title {
            get {
                return ResourceManager.GetString("Surveys Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        internal static string User_ID_Label {
            get {
                return ResourceManager.GetString("User ID Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to {0}.
        /// </summary>
        internal static string Welcome_Text {
            get {
                return ResourceManager.GetString("Welcome Text", resourceCulture);
            }
        }
    }
}
