//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSIDE.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSIDE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t find the page you were looking for. Check your link and try again, or get in touch with the system administrators..
        /// </summary>
        public static string _404_Error_Text {
            get {
                return ResourceManager.GetString("404 Error Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page not found.
        /// </summary>
        public static string _404_Error_Title {
            get {
                return ResourceManager.GetString("404 Error Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like you don&apos;t have access to this page. Contact your system administrator to request access.
        /// </summary>
        public static string Access_Denied_Text {
            get {
                return ResourceManager.GetString("Access Denied Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied.
        /// </summary>
        public static string Access_Denied_Title {
            get {
                return ResourceManager.GetString("Access Denied Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account details and password are managed by your identity provider..
        /// </summary>
        public static string Account_Details_Text {
            get {
                return ResourceManager.GetString("Account Details Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add comment.
        /// </summary>
        public static string Add_Comment_Label {
            get {
                return ResourceManager.GetString("Add Comment Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add contact.
        /// </summary>
        public static string Add_Contact_Label {
            get {
                return ResourceManager.GetString("Add Contact Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add infrastructure by ID.
        /// </summary>
        public static string Add_Infrastructure_By_ID_Title {
            get {
                return ResourceManager.GetString("Add Infrastructure By ID Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add infrastructure link.
        /// </summary>
        public static string Add_Infrastructure_Link_Label {
            get {
                return ResourceManager.GetString("Add Infrastructure Link Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add nearby infrastructure.
        /// </summary>
        public static string Add_Nearby_Infrastructure_Title {
            get {
                return ResourceManager.GetString("Add Nearby Infrastructure Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All nearby infrastructure has already been linked to this maintenance job.
        /// </summary>
        public static string All_Nearby_Infrastructure_Linked_Message {
            get {
                return ResourceManager.GetString("All Nearby Infrastructure Linked Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approximate Length.
        /// </summary>
        public static string Approximate_Length_Label {
            get {
                return ResourceManager.GetString("Approximate Length Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned to team.
        /// </summary>
        public static string Assigned_To_Team_Label {
            get {
                return ResourceManager.GetString("Assigned To Team Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to fill in at least one contact detail.
        /// </summary>
        public static string At_Least_One_Contact_Property_Validation_Message {
            get {
                return ResourceManager.GetString("At Least One Contact Property Validation Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Details.
        /// </summary>
        public static string Basic_Details_Label {
            get {
                return ResourceManager.GetString("Basic Details Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel_Label {
            get {
                return ResourceManager.GetString("Cancel Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reopening date.
        /// </summary>
        public static string Closure_End_Date_Label {
            get {
                return ResourceManager.GetString("Closure End Date Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reopening date has passed.
        /// </summary>
        public static string Closure_End_Date_Passed_Short_Warning_Text {
            get {
                return ResourceManager.GetString("Closure End Date Passed Short Warning Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This path was supposed to reopen {0}. Reopen the path or update the reopening date.
        /// </summary>
        public static string Closure_End_Date_Passed_Warning_Text {
            get {
                return ResourceManager.GetString("Closure End Date Passed Warning Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed indefinitely?.
        /// </summary>
        public static string Closure_Is_Indefinite_Label {
            get {
                return ResourceManager.GetString("Closure Is Indefinite Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closure start date.
        /// </summary>
        public static string Closure_Start_Date_Label {
            get {
                return ResourceManager.GetString("Closure Start Date Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} at {1}.
        /// </summary>
        public static string Comment_Author_Title {
            get {
                return ResourceManager.GetString("Comment Author Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment_Label {
            get {
                return ResourceManager.GetString("Comment Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments ({0}).
        /// </summary>
        public static string Comments_Label {
            get {
                return ResourceManager.GetString("Comments Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed date from.
        /// </summary>
        public static string Completed_Date_From_Label {
            get {
                return ResourceManager.GetString("Completed Date From Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed date to.
        /// </summary>
        public static string Completed_Date_To_Label {
            get {
                return ResourceManager.GetString("Completed Date To Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completion date.
        /// </summary>
        public static string Completion_Date_Label {
            get {
                return ResourceManager.GetString("Completion Date Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update {0}. The data has been modified by another user. Please reload the page..
        /// </summary>
        public static string Concurrency_Error_Message {
            get {
                return ResourceManager.GetString("Concurrency Error Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact_Label {
            get {
                return ResourceManager.GetString("Contact Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation.
        /// </summary>
        public static string Contact_Organisation_Label {
            get {
                return ResourceManager.GetString("Contact Organisation Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact type.
        /// </summary>
        public static string Contact_Type_Label {
            get {
                return ResourceManager.GetString("Contact Type Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts ({0}).
        /// </summary>
        public static string Contacts_Label {
            get {
                return ResourceManager.GetString("Contacts Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create_Label {
            get {
                return ResourceManager.GetString("Create Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new infrastructure.
        /// </summary>
        public static string Create_New_Infrastructure_Label {
            get {
                return ResourceManager.GetString("Create New Infrastructure Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an infrastructure item to the database by adding it to the map and filling in the relevant details..
        /// </summary>
        public static string Create_New_Infrastructure_Text {
            get {
                return ResourceManager.GetString("Create New Infrastructure Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new job.
        /// </summary>
        public static string Create_New_Job_Label {
            get {
                return ResourceManager.GetString("Create New Job Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a job to the maintenance database by adding it to the map and filling in the relevant details..
        /// </summary>
        public static string Create_New_Job_Text {
            get {
                return ResourceManager.GetString("Create New Job Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new Right of Way.
        /// </summary>
        public static string Create_New_Right_of_Way_Label {
            get {
                return ResourceManager.GetString("Create New Right of Way Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new Right of Way by drawing the line on a map and adding the details..
        /// </summary>
        public static string Create_New_Right_of_Way_Text {
            get {
                return ResourceManager.GetString("Create New Right of Way Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this comment?.
        /// </summary>
        public static string Delete_Comment_Confirmation {
            get {
                return ResourceManager.GetString("Delete Comment Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this contact?.
        /// </summary>
        public static string Delete_Contact_Confirmation {
            get {
                return ResourceManager.GetString("Delete Contact Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to unlink this infrastructure from the maintenance job?.
        /// </summary>
        public static string Delete_Infra_Link_Confirmation {
            get {
                return ResourceManager.GetString("Delete Infra Link Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete_Label {
            get {
                return ResourceManager.GetString("Delete Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this file?.
        /// </summary>
        public static string Delete_Media_Confirmation {
            get {
                return ResourceManager.GetString("Delete Media Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name.
        /// </summary>
        public static string Display_Name_Label {
            get {
                return ResourceManager.GetString("Display Name Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DMMO.
        /// </summary>
        public static string DMMO_Abbreviation {
            get {
                return ResourceManager.GetString("DMMO Abbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definitive Map Modification Orders.
        /// </summary>
        public static string DMMO_Full_Text {
            get {
                return ResourceManager.GetString("DMMO Full Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string Documents_Label {
            get {
                return ResourceManager.GetString("Documents Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download_Label {
            get {
                return ResourceManager.GetString("Download Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate of.
        /// </summary>
        public static string Duplicate_Job_ID_Label {
            get {
                return ResourceManager.GetString("Duplicate Job ID Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easting.
        /// </summary>
        public static string Easting_Label {
            get {
                return ResourceManager.GetString("Easting Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit contact details.
        /// </summary>
        public static string Edit_Contact_Title {
            get {
                return ResourceManager.GetString("Edit Contact Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit_Label {
            get {
                return ResourceManager.GetString("Edit Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string Email_Label {
            get {
                return ResourceManager.GetString("Email Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Easting.
        /// </summary>
        public static string End_Easting_Label {
            get {
                return ResourceManager.GetString("End Easting Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Northing.
        /// </summary>
        public static string End_Northing_Label {
            get {
                return ResourceManager.GetString("End Northing Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! Something went wrong.
        /// </summary>
        public static string Error_Header_Text {
            get {
                return ResourceManager.GetString("Error Header Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error dealing with your request. If this continues to happen, get in touch with your system administrator.
        /// </summary>
        public static string Error_Text {
            get {
                return ResourceManager.GetString("Error Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error_Title {
            get {
                return ResourceManager.GetString("Error Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max file size of {0}MB exceeded for file &apos;{1}&apos;.
        /// </summary>
        public static string File_Too_Large_Upload_Error {
            get {
                return ResourceManager.GetString("File Too Large Upload Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error showing this data that we weren&apos;t expecting. Reload the page to try again, or contact your system administrator if the problem persists..
        /// </summary>
        public static string General_Component_Error_Message {
            get {
                return ResourceManager.GetString("General Component Error Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred that we weren&apos;t expecting. Reload the page to try again..
        /// </summary>
        public static string General_Error_Message {
            get {
                return ResourceManager.GetString("General Error Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location you chose is outside of the UK.
        /// </summary>
        public static string Geometry_Outside_UK_Validation_Message {
            get {
                return ResourceManager.GetString("Geometry Outside UK Validation Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide previous statements.
        /// </summary>
        public static string Hide_Previous_Statements_Label {
            get {
                return ResourceManager.GetString("Hide Previous Statements Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home_Title {
            get {
                return ResourceManager.GetString("Home Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity provider.
        /// </summary>
        public static string Identity_Provider_Label {
            get {
                return ResourceManager.GetString("Identity Provider Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string Images_Label {
            get {
                return ResourceManager.GetString("Images Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This path is closed indefinitely.
        /// </summary>
        public static string Indefinite_Closure_Text {
            get {
                return ResourceManager.GetString("Indefinite Closure Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new infrastructure item.
        /// </summary>
        public static string Infrastructure_Create_Title {
            get {
                return ResourceManager.GetString("Infrastructure Create Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Infrastructure_Description_Label {
            get {
                return ResourceManager.GetString("Infrastructure Description Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infrastructure Details {0}.
        /// </summary>
        public static string Infrastructure_Details_Title {
            get {
                return ResourceManager.GetString("Infrastructure Details Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No infrastructure with that ID could be found.
        /// </summary>
        public static string Infrastructure_Does_Not_Exist_Validation_Message {
            get {
                return ResourceManager.GetString("Infrastructure Does Not Exist Validation Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Infrastructure Item {0}.
        /// </summary>
        public static string Infrastructure_Edit_Title {
            get {
                return ResourceManager.GetString("Infrastructure Edit Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height (m).
        /// </summary>
        public static string Infrastructure_Height_Label {
            get {
                return ResourceManager.GetString("Infrastructure Height Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infrastructure ID.
        /// </summary>
        public static string Infrastructure_ID_Label {
            get {
                return ResourceManager.GetString("Infrastructure ID Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation date.
        /// </summary>
        public static string Infrastructure_Installation_Date_Label {
            get {
                return ResourceManager.GetString("Infrastructure Installation Date Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length (m).
        /// </summary>
        public static string Infrastructure_Length_Label {
            get {
                return ResourceManager.GetString("Infrastructure Length Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Infrastructure_Name_Label {
            get {
                return ResourceManager.GetString("Infrastructure Name Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infrastructure with ID &apos;{0}&apos; was not found in the database.
        /// </summary>
        public static string Infrastructure_Not_Found_Error_Message {
            get {
                return ResourceManager.GetString("Infrastructure Not Found Error Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infrastructure.
        /// </summary>
        public static string Infrastructure_Title {
            get {
                return ResourceManager.GetString("Infrastructure Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infrastructure type.
        /// </summary>
        public static string Infrastructure_Type_Label {
            get {
                return ResourceManager.GetString("Infrastructure Type Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width (m).
        /// </summary>
        public static string Infrastructure_Width_Label {
            get {
                return ResourceManager.GetString("Infrastructure Width Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infrastructure ({0}).
        /// </summary>
        public static string Infrastructure_With_Count_Title {
            get {
                return ResourceManager.GetString("Infrastructure With Count Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation date from.
        /// </summary>
        public static string Installation_Date_From_Label {
            get {
                return ResourceManager.GetString("Installation Date From Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation date to.
        /// </summary>
        public static string Installation_Date_To_Label {
            get {
                return ResourceManager.GetString("Installation Date To Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closure end date must be after start date.
        /// </summary>
        public static string Invalid_Closure_Dates_Validation_Message {
            get {
                return ResourceManager.GetString("Invalid Closure Dates Validation Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your geometry is not valid. Redraw your geometry, and if you still have issues, contact your system administrator.
        /// </summary>
        public static string Invalid_Geometry_Validation_Message {
            get {
                return ResourceManager.GetString("Invalid Geometry Validation Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publicly viewable?.
        /// </summary>
        public static string Is_Public_Label {
            get {
                return ResourceManager.GetString("Is Public Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job ID.
        /// </summary>
        public static string Job_ID_Label {
            get {
                return ResourceManager.GetString("Job ID Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string Job_Priority_Label {
            get {
                return ResourceManager.GetString("Job Priority Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Job_Status_Label {
            get {
                return ResourceManager.GetString("Job Status Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landowner Deposits.
        /// </summary>
        public static string Landowner_Deposits_Title {
            get {
                return ResourceManager.GetString("Landowner Deposits Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal status.
        /// </summary>
        public static string Legal_Status_Label {
            get {
                return ResourceManager.GetString("Legal Status Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading_Text {
            get {
                return ResourceManager.GetString("Loading Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log date from.
        /// </summary>
        public static string Log_Date_From_Label {
            get {
                return ResourceManager.GetString("Log Date From Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log date.
        /// </summary>
        public static string Log_Date_Label {
            get {
                return ResourceManager.GetString("Log Date Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log date to.
        /// </summary>
        public static string Log_Date_To_Label {
            get {
                return ResourceManager.GetString("Log Date To Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged by.
        /// </summary>
        public static string Logged_By_Label {
            get {
                return ResourceManager.GetString("Logged By Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout_Label {
            get {
                return ResourceManager.GetString("Logout Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new maintenance job.
        /// </summary>
        public static string Maintenance_Create_Title {
            get {
                return ResourceManager.GetString("Maintenance Create Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Job {0}.
        /// </summary>
        public static string Maintenance_Details_Title {
            get {
                return ResourceManager.GetString("Maintenance Details Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Maintenance Job {0}.
        /// </summary>
        public static string Maintenance_Edit_Title {
            get {
                return ResourceManager.GetString("Maintenance Edit Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance job with ID &apos;{0}&apos; was not found in the database.
        /// </summary>
        public static string Maintenance_Job_Not_Found_Error_Message {
            get {
                return ResourceManager.GetString("Maintenance Job Not Found Error Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance team.
        /// </summary>
        public static string Maintenance_Team_Label {
            get {
                return ResourceManager.GetString("Maintenance Team Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance.
        /// </summary>
        public static string Maintenance_Title {
            get {
                return ResourceManager.GetString("Maintenance Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage application.
        /// </summary>
        public static string Manage_Application_Label {
            get {
                return ResourceManager.GetString("Manage Application Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media ({0}).
        /// </summary>
        public static string Media_Label {
            get {
                return ResourceManager.GetString("Media Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify statement.
        /// </summary>
        public static string Modify_Statement_Label {
            get {
                return ResourceManager.GetString("Modify Statement Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select multiple entries by holding down Ctrl on your keyboard.
        /// </summary>
        public static string Multi_Select_Instructions_Text {
            get {
                return ResourceManager.GetString("Multi Select Instructions Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This route goes across multiple parishes. We&apos;ve set the route code based on which parish the route is most within, which is &apos;{0}&apos;. You may want to check this is what you want..
        /// </summary>
        public static string Multiple_Parish_Codes_Found_Error_Message {
            get {
                return ResourceManager.GetString("Multiple Parish Codes Found Error Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My account.
        /// </summary>
        public static string My_Account_Label {
            get {
                return ResourceManager.GetString("My Account Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My roles.
        /// </summary>
        public static string My_Roles_Header {
            get {
                return ResourceManager.GetString("My Roles Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name_Label {
            get {
                return ResourceManager.GetString("Name Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new comment.
        /// </summary>
        public static string New_Comment_Label {
            get {
                return ResourceManager.GetString("New Comment Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None of your files were uploaded.
        /// </summary>
        public static string No_Files_Uploaded_Error {
            get {
                return ResourceManager.GetString("No Files Uploaded Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No infrastructure could be found nearby.
        /// </summary>
        public static string No_Infrastructure_Nearby_Message {
            get {
                return ResourceManager.GetString("No Infrastructure Nearby Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No infrastructure is linked to this job.
        /// </summary>
        public static string No_Job_Infra_Message {
            get {
                return ResourceManager.GetString("No Job Infra Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No comments for this maintenance item..
        /// </summary>
        public static string No_Maintenance_Comments_Message {
            get {
                return ResourceManager.GetString("No Maintenance Comments Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No contacts for this maintenance job.
        /// </summary>
        public static string No_Maintenance_Contacts_Message {
            get {
                return ResourceManager.GetString("No Maintenance Contacts Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no related media.
        /// </summary>
        public static string No_Media_Message {
            get {
                return ResourceManager.GetString("No Media Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No parishes could be found that contain this route.
        /// </summary>
        public static string No_Parish_Found_Error_Message {
            get {
                return ResourceManager.GetString("No Parish Found Error Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found.
        /// </summary>
        public static string No_Results_Found_Label {
            get {
                return ResourceManager.GetString("No Results Found Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can either redraw your point nearer to a route, or fill in the Route ID manually..
        /// </summary>
        public static string No_Rights_of_Way_Near_Geometry_Options_Text {
            get {
                return ResourceManager.GetString("No Rights of Way Near Geometry Options Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no routes near where you clicked. .
        /// </summary>
        public static string No_Rights_of_Way_Near_Geometry_Validation_Message {
            get {
                return ResourceManager.GetString("No Rights of Way Near Geometry Validation Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any roles assigned to you.
        /// </summary>
        public static string No_Roles_Text {
            get {
                return ResourceManager.GetString("No Roles Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No infrastructure has been recorded on this route.
        /// </summary>
        public static string No_Route_Infra_Message {
            get {
                return ResourceManager.GetString("No Route Infra Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No statements found for this Right of Way.
        /// </summary>
        public static string No_Statements_Message {
            get {
                return ResourceManager.GetString("No Statements Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Northing.
        /// </summary>
        public static string Northing_Label {
            get {
                return ResourceManager.GetString("Northing Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        public static string Not_Public_Label {
            get {
                return ResourceManager.GetString("Not Public Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operational status.
        /// </summary>
        public static string Operational_Status_Label {
            get {
                return ResourceManager.GetString("Operational Status Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation.
        /// </summary>
        public static string Organisation_Name_Label {
            get {
                return ResourceManager.GetString("Organisation Name Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parish.
        /// </summary>
        public static string Parish_Label {
            get {
                return ResourceManager.GetString("Parish Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of your files were not uploaded.
        /// </summary>
        public static string Partial_File_Upload_Error {
            get {
                return ResourceManager.GetString("Partial File Upload Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path type.
        /// </summary>
        public static string Path_Type_Label {
            get {
                return ResourceManager.GetString("Path Type Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPO.
        /// </summary>
        public static string PPO_Abbreviation {
            get {
                return ResourceManager.GetString("PPO Abbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Path Orders.
        /// </summary>
        public static string PPO_Full_Text {
            get {
                return ResourceManager.GetString("PPO Full Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary contact number.
        /// </summary>
        public static string Primary_Contact_Number_Label {
            get {
                return ResourceManager.GetString("Primary Contact Number Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem description.
        /// </summary>
        public static string Problem_Description_Label {
            get {
                return ResourceManager.GetString("Problem Description Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem types.
        /// </summary>
        public static string Problem_Types_Label {
            get {
                return ResourceManager.GetString("Problem Types Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This comment will be visible to members of the public and (if new) will be emailed to subscribers. Make sure personal details are removed and the comment is appropriately written..
        /// </summary>
        public static string Public_Comment_Warning_Text {
            get {
                return ResourceManager.GetString("Public Comment Warning Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        public static string Public_Label {
            get {
                return ResourceManager.GetString("Public Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redraw.
        /// </summary>
        public static string Redraw_Label {
            get {
                return ResourceManager.GetString("Redraw Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string Reload_Label {
            get {
                return ResourceManager.GetString("Reload Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Rights of Way with ID &apos;{0}&apos; could be found.
        /// </summary>
        public static string Right_of_Way_Not_Found_Error_Message {
            get {
                return ResourceManager.GetString("Right of Way Not Found Error Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right of Way {0}.
        /// </summary>
        public static string Rights_of_Way_Details_Title {
            get {
                return ResourceManager.GetString("Rights of Way Details Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Right of Way {0}.
        /// </summary>
        public static string Rights_of_Way_Edit_Title {
            get {
                return ResourceManager.GetString("Rights of Way Edit Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rights of Way.
        /// </summary>
        public static string Rights_of_Way_Title {
            get {
                return ResourceManager.GetString("Rights of Way Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These are the roles that have been assigned to you by your system administrator. They control what you can and can&apos;t do in the app..
        /// </summary>
        public static string Roles_List_Text {
            get {
                return ResourceManager.GetString("Roles List Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate clockwise.
        /// </summary>
        public static string Rotate_Clockwise_Label {
            get {
                return ResourceManager.GetString("Rotate Clockwise Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate counter clockwise.
        /// </summary>
        public static string Rotate_Counter_Clockwise_Label {
            get {
                return ResourceManager.GetString("Rotate Counter Clockwise Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closure notices.
        /// </summary>
        public static string Route_Closure_Documents_Label {
            get {
                return ResourceManager.GetString("Route Closure Documents Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route with ID &apos;{0}&apos; already exists.
        /// </summary>
        public static string Route_Code_Not_Unique_Validation_Message {
            get {
                return ResourceManager.GetString("Route Code Not Unique Validation Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route &apos;{0}&apos; does not exist in the database.
        /// </summary>
        public static string Route_Does_Not_Exist_Validation_Message {
            get {
                return ResourceManager.GetString("Route Does Not Exist Validation Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route code.
        /// </summary>
        public static string Route_ID_Label {
            get {
                return ResourceManager.GetString("Route ID Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Route ID manually.
        /// </summary>
        public static string Route_ID_Manual_Entry_Label {
            get {
                return ResourceManager.GetString("Route ID Manual Entry Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem saving this data. Try again or contact your system administrator..
        /// </summary>
        public static string Save_Error_Message {
            get {
                return ResourceManager.GetString("Save Error Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save_Label {
            get {
                return ResourceManager.GetString("Save Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search again.
        /// </summary>
        public static string Search_Again_Label {
            get {
                return ResourceManager.GetString("Search Again Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search infrastructure database.
        /// </summary>
        public static string Search_Infrastructure_Title {
            get {
                return ResourceManager.GetString("Search Infrastructure Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for maintenance jobs.
        /// </summary>
        public static string Search_Jobs_Title {
            get {
                return ResourceManager.GetString("Search Jobs Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search_Label {
            get {
                return ResourceManager.GetString("Search Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of results ({0}) are shown. To see all results of a search please narrow your search criteria..
        /// </summary>
        public static string Search_Results_Limit_Text {
            get {
                return ResourceManager.GetString("Search Results Limit Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search results.
        /// </summary>
        public static string Search_Results_Title {
            get {
                return ResourceManager.GetString("Search Results Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for a Right of Way.
        /// </summary>
        public static string Search_Rights_of_Way_Title {
            get {
                return ResourceManager.GetString("Search Rights of Way Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one search field should be filled in.
        /// </summary>
        public static string Search_Validation_At_Least_One_Message {
            get {
                return ResourceManager.GetString("Search Validation At Least One Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must not be in the future.
        /// </summary>
        public static string Search_Validation_Date_Not_In_Future_Message {
            get {
                return ResourceManager.GetString("Search Validation Date Not In Future Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary contact number.
        /// </summary>
        public static string Secondary_Contact_Number_Label {
            get {
                return ResourceManager.GetString("Secondary Contact Number Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select multiple parishes.
        /// </summary>
        public static string Select_Multiple_Parishes_Label {
            get {
                return ResourceManager.GetString("Select Multiple Parishes Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show previous statements.
        /// </summary>
        public static string Show_Previous_Statements_Label {
            get {
                return ResourceManager.GetString("Show Previous Statements Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Easting.
        /// </summary>
        public static string Start_Easting_Label {
            get {
                return ResourceManager.GetString("Start Easting Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Northing.
        /// </summary>
        public static string Start_Northing_Label {
            get {
                return ResourceManager.GetString("Start Northing Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Grid Ref.
        /// </summary>
        public static string Statement_End_Grid_Ref_Label {
            get {
                return ResourceManager.GetString("Statement End Grid Ref Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Grid Ref.
        /// </summary>
        public static string Statement_Start_Grid_Ref_Label {
            get {
                return ResourceManager.GetString("Statement Start Grid Ref Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement Text.
        /// </summary>
        public static string Statement_Text_Label {
            get {
                return ResourceManager.GetString("Statement Text Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement.
        /// </summary>
        public static string Statements_Title {
            get {
                return ResourceManager.GetString("Statements Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surveys.
        /// </summary>
        public static string Surveys_Title {
            get {
                return ResourceManager.GetString("Surveys Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title_Label {
            get {
                return ResourceManager.GetString("Title Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle.
        /// </summary>
        public static string Toggle_Label {
            get {
                return ResourceManager.GetString("Toggle Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only upload a maximum of {0} files at once.
        /// </summary>
        public static string Too_Many_Files_Upload_Error {
            get {
                return ResourceManager.GetString("Too Many Files Upload Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update_Label {
            get {
                return ResourceManager.GetString("Update Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload closure notices.
        /// </summary>
        public static string Upload_Closure_Notification_Document_Title {
            get {
                return ResourceManager.GetString("Upload Closure Notification Document Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded.
        /// </summary>
        public static string Upload_Date_Label {
            get {
                return ResourceManager.GetString("Upload Date Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click or drag and drop files into the box below to upload. You can add up to {0} files at once, maximum {1}MB per file. If you are on a mobile device you can take a photo or video directly from the button below..
        /// </summary>
        public static string Upload_Explanatory_Text {
            get {
                return ResourceManager.GetString("Upload Explanatory Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; was not uploaded.
        /// </summary>
        public static string Upload_Failure_Message {
            get {
                return ResourceManager.GetString("Upload Failure Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload File.
        /// </summary>
        public static string Upload_File_Label {
            get {
                return ResourceManager.GetString("Upload File Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload other media.
        /// </summary>
        public static string Upload_Other_Media_Title {
            get {
                return ResourceManager.GetString("Upload Other Media Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} file(s) successfully uploaded.
        /// </summary>
        public static string Upload_Success_Message {
            get {
                return ResourceManager.GetString("Upload Success Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading.
        /// </summary>
        public static string Uploading_Text {
            get {
                return ResourceManager.GetString("Uploading Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        public static string User_ID_Label {
            get {
                return ResourceManager.GetString("User ID Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos.
        /// </summary>
        public static string Videos_Label {
            get {
                return ResourceManager.GetString("Videos Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all recent incomplete jobs.
        /// </summary>
        public static string View_All_Recent_Jobs_Label {
            get {
                return ResourceManager.GetString("View All Recent Jobs Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to {0}.
        /// </summary>
        public static string Welcome_Text {
            get {
                return ResourceManager.GetString("Welcome Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work done.
        /// </summary>
        public static string Work_Done_Label {
            get {
                return ResourceManager.GetString("Work Done Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days ago.
        /// </summary>
        public static string X_Days_Ago_Label {
            get {
                return ResourceManager.GetString("X Days Ago Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}m away.
        /// </summary>
        public static string X_Metres_Away_Label {
            get {
                return ResourceManager.GetString("X Metres Away Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yesterday.
        /// </summary>
        public static string Yesterday_Label {
            get {
                return ResourceManager.GetString("Yesterday Label", resourceCulture);
            }
        }
    }
}
