//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSIDE.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSIDE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like you don&apos;t have access to this page. Contact your system administrator to request access.
        /// </summary>
        public static string Access_Denied_Text {
            get {
                return ResourceManager.GetString("Access Denied Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied.
        /// </summary>
        public static string Access_Denied_Title {
            get {
                return ResourceManager.GetString("Access Denied Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account details and password are managed by your identity provider..
        /// </summary>
        public static string Account_Details_Text {
            get {
                return ResourceManager.GetString("Account Details Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned to team.
        /// </summary>
        public static string Assigned_To_Team_Label {
            get {
                return ResourceManager.GetString("Assigned To Team Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel_Label {
            get {
                return ResourceManager.GetString("Cancel Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed date from.
        /// </summary>
        public static string Completed_Date_From_Label {
            get {
                return ResourceManager.GetString("Completed Date From Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed date to.
        /// </summary>
        public static string Completed_Date_To_Label {
            get {
                return ResourceManager.GetString("Completed Date To Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completion date.
        /// </summary>
        public static string Completion_Date_Label {
            get {
                return ResourceManager.GetString("Completion Date Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update {0}. The data has been modified by another user. Please reload the page..
        /// </summary>
        public static string Concurrency_Error_Message {
            get {
                return ResourceManager.GetString("Concurrency Error Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create_Label {
            get {
                return ResourceManager.GetString("Create Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new job.
        /// </summary>
        public static string Create_New_Job_Label {
            get {
                return ResourceManager.GetString("Create New Job Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a job to the maintenance database by adding it to the map and filling in the relevant details..
        /// </summary>
        public static string Create_New_Job_Text {
            get {
                return ResourceManager.GetString("Create New Job Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name.
        /// </summary>
        public static string Display_Name_Label {
            get {
                return ResourceManager.GetString("Display Name Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DMMO.
        /// </summary>
        public static string DMMO_Abbreviation {
            get {
                return ResourceManager.GetString("DMMO Abbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definitive Map Modification Orders.
        /// </summary>
        public static string DMMO_Full_Text {
            get {
                return ResourceManager.GetString("DMMO Full Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easting.
        /// </summary>
        public static string Easting_Label {
            get {
                return ResourceManager.GetString("Easting Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit_Label {
            get {
                return ResourceManager.GetString("Edit Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! Something went wrong.
        /// </summary>
        public static string Error_Header_Text {
            get {
                return ResourceManager.GetString("Error Header Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error dealing with your request. If this continues to happen, get in touch with your system administrator.
        /// </summary>
        public static string Error_Text {
            get {
                return ResourceManager.GetString("Error Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error_Title {
            get {
                return ResourceManager.GetString("Error Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home_Title {
            get {
                return ResourceManager.GetString("Home Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infrastructure.
        /// </summary>
        public static string Infrastructure_Title {
            get {
                return ResourceManager.GetString("Infrastructure Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your geometry is not valid. Redraw your geometry, and if you still have issues, contact your system administrator.
        /// </summary>
        public static string Invalid_Geometry_Validation_Message {
            get {
                return ResourceManager.GetString("Invalid Geometry Validation Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job ID.
        /// </summary>
        public static string Job_ID_Label {
            get {
                return ResourceManager.GetString("Job ID Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string Job_Priority_Label {
            get {
                return ResourceManager.GetString("Job Priority Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Job_Status_Label {
            get {
                return ResourceManager.GetString("Job Status Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landowner Deposits.
        /// </summary>
        public static string Landowner_Deposits_Title {
            get {
                return ResourceManager.GetString("Landowner Deposits Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading_Text {
            get {
                return ResourceManager.GetString("Loading Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log date from.
        /// </summary>
        public static string Log_Date_From_Label {
            get {
                return ResourceManager.GetString("Log Date From Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log date.
        /// </summary>
        public static string Log_Date_Label {
            get {
                return ResourceManager.GetString("Log Date Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log date to.
        /// </summary>
        public static string Log_Date_To_Label {
            get {
                return ResourceManager.GetString("Log Date To Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged by.
        /// </summary>
        public static string Logged_By_Label {
            get {
                return ResourceManager.GetString("Logged By Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout_Label {
            get {
                return ResourceManager.GetString("Logout Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new maintenance job.
        /// </summary>
        public static string Maintenance_Create_Title {
            get {
                return ResourceManager.GetString("Maintenance Create Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Job {0}.
        /// </summary>
        public static string Maintenance_Details_Title {
            get {
                return ResourceManager.GetString("Maintenance Details Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Maintenance Job {0}.
        /// </summary>
        public static string Maintenance_Edit_Title {
            get {
                return ResourceManager.GetString("Maintenance Edit Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance job with ID &apos;{0}&apos; was not found in the database.
        /// </summary>
        public static string Maintenance_Job_Not_Found_Error_Message {
            get {
                return ResourceManager.GetString("Maintenance Job Not Found Error Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance.
        /// </summary>
        public static string Maintenance_Title {
            get {
                return ResourceManager.GetString("Maintenance Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage application.
        /// </summary>
        public static string Manage_Application_Label {
            get {
                return ResourceManager.GetString("Manage Application Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My account.
        /// </summary>
        public static string My_Account_Label {
            get {
                return ResourceManager.GetString("My Account Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My roles.
        /// </summary>
        public static string My_Roles_Header {
            get {
                return ResourceManager.GetString("My Roles Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found.
        /// </summary>
        public static string No_Results_Found_Label {
            get {
                return ResourceManager.GetString("No Results Found Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can either redraw your point nearer to a route, or fill in the Route ID manually..
        /// </summary>
        public static string No_Rights_of_Way_Near_Geometry_Options_Text {
            get {
                return ResourceManager.GetString("No Rights of Way Near Geometry Options Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no routes near where you clicked. .
        /// </summary>
        public static string No_Rights_of_Way_Near_Geometry_Validation_Message {
            get {
                return ResourceManager.GetString("No Rights of Way Near Geometry Validation Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any roles assigned to you.
        /// </summary>
        public static string No_Roles_Text {
            get {
                return ResourceManager.GetString("No Roles Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Northing.
        /// </summary>
        public static string Northing_Label {
            get {
                return ResourceManager.GetString("Northing Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parish.
        /// </summary>
        public static string Parish_Label {
            get {
                return ResourceManager.GetString("Parish Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPO.
        /// </summary>
        public static string PPO_Abbreviation {
            get {
                return ResourceManager.GetString("PPO Abbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Path Orders.
        /// </summary>
        public static string PPO_Full_Text {
            get {
                return ResourceManager.GetString("PPO Full Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary email address.
        /// </summary>
        public static string Primary_Email_Label {
            get {
                return ResourceManager.GetString("Primary Email Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem description.
        /// </summary>
        public static string Problem_Description_Label {
            get {
                return ResourceManager.GetString("Problem Description Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rights of Way.
        /// </summary>
        public static string Rights_of_Way_Title {
            get {
                return ResourceManager.GetString("Rights of Way Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These are the roles that have been assigned to you by your system administrator. They control what you can and can&apos;t do in the app..
        /// </summary>
        public static string Roles_List_Text {
            get {
                return ResourceManager.GetString("Roles List Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route &apos;{0}&apos; does not exist in the database.
        /// </summary>
        public static string Route_Does_Not_Exist_Validation_Message {
            get {
                return ResourceManager.GetString("Route Does Not Exist Validation Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route code.
        /// </summary>
        public static string Route_ID_Label {
            get {
                return ResourceManager.GetString("Route ID Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search again.
        /// </summary>
        public static string Search_Again_Label {
            get {
                return ResourceManager.GetString("Search Again Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for maintenance jobs.
        /// </summary>
        public static string Search_Jobs_Title {
            get {
                return ResourceManager.GetString("Search Jobs Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search_Label {
            get {
                return ResourceManager.GetString("Search Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search results.
        /// </summary>
        public static string Search_Results_Title {
            get {
                return ResourceManager.GetString("Search Results Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one search field should be filled in.
        /// </summary>
        public static string Search_Validation_At_Least_One_Message {
            get {
                return ResourceManager.GetString("Search Validation At Least One Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must not be in the future.
        /// </summary>
        public static string Search_Validation_Date_Not_In_Future_Message {
            get {
                return ResourceManager.GetString("Search Validation Date Not In Future Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surveys.
        /// </summary>
        public static string Surveys_Title {
            get {
                return ResourceManager.GetString("Surveys Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update_Label {
            get {
                return ResourceManager.GetString("Update Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        public static string User_ID_Label {
            get {
                return ResourceManager.GetString("User ID Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all recent unactioned jobs.
        /// </summary>
        public static string View_All_Recent_Jobs_Label {
            get {
                return ResourceManager.GetString("View All Recent Jobs Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to {0}.
        /// </summary>
        public static string Welcome_Text {
            get {
                return ResourceManager.GetString("Welcome Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work done.
        /// </summary>
        public static string Work_Done_Label {
            get {
                return ResourceManager.GetString("Work Done Label", resourceCulture);
            }
        }
    }
}
